# Generated by Django 2.0 on 2018-09-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_auto_20180922_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
