# Generated by Django 2.0 on 2018-09-25 19:00

import blogger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_auto_20180922_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_pic',
            field=models.FileField(max_length=500, upload_to=blogger.models.profile_pic_path),
        ),
    ]
