# Generated by Django 2.0 on 2018-09-30 06:29

import blogger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0008_auto_20180929_1200'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='userprofile',
        #    name='id',
        #),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_pic',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=blogger.models.profile_pic_path),
        ),
    ]
